# Generated by Django 2.1.7 on 2019-04-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190330_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
