# Generated by Django 2.1.7 on 2019-03-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('Laptops', 'Laptops'), ('Storage', 'storage'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion')], max_length=2)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('IN USE', 'In use')], default='Free', max_length=2)),
                ('condition', models.CharField(choices=[('USABLE', 'Usable'), ('FAULTY', 'faulty')], default='Usable', max_length=2)),
            ],
        ),
    ]
