# Generated by Django 2.1.7 on 2019-03-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('USABLE', 'Usable'), ('FAULTY', 'faulty')], default='Usable', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('IN USE', 'In use')], default='Free', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Laptops', 'Laptops'), ('Storage', 'storage'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion')], max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
