# Generated by Django 2.1.7 on 2019-03-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190321_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
