# Generated by Django 2.1.7 on 2019-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='tid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
