# Generated by Django 2.1.7 on 2019-03-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20190328_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='crtid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
