# Generated by Django 2.1.7 on 2019-03-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190322_1252'),
        ('cart', '0003_auto_20190326_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='product.Product'),
        ),
    ]
