# Generated by Django 2.1.7 on 2019-03-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_cart_cartid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.AddField(
            model_name='cart',
            name='crtid',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
        ),
    ]
