# Generated by Django 2.1.7 on 2019-03-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_auto_20190328_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='crtid',
            field=models.CharField(max_length=20),
        ),
    ]
